MACBOOK_MONITOR = 'Color LCD'

ROOM_LEFT_MONITOR = 'C34H89x'
ROOM_RIGHT_MONITOR = 'DELL U2717D'
OFFICE_LEFT_MONITOR = 'C34H89x'
OFFICE_RIGHT_MONITOR = 'DELL U2717D'


IDEs = {
  'Emacs',
  'DrRacket',
}
